First attempt at porting FirebaseSignInWithGoogle to WearOS
The WearOS code compiles and runs but fails with the below error that is not a good sign. :/
I may need to find a stand-alone Firebase Auth Google Account example for WearOS to prove that this is even possible.
I suspect Firebase Auth Google Account must be invoked on the phone. :/
```
oneTapSignInWithGoogle: EXCEPTION
com.google.android.gms.common.api.ApiException: 17: API: Auth.Api.Identity.SignIn.API is not available on this device. Connection failed with: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@18.0.1:3)
at com.google.android.gms.common.api.internal.ApiExceptionMapper.getException(com.google.android.gms:play-services-base@@18.0.1:1)
at com.google.android.gms.common.api.internal.zag.zad(com.google.android.gms:play-services-base@@18.0.1:1) with tag AuthRepositoryImpl
```